### PR TITLE
Fixed typos in Poisson Transient driver

### PR DESCRIPTION
**Pull request by ericneiva**
Hi, @fverdugo,

I found a couple of obvious typos in the Poisson transient driver.

Could you please review and merge whenever you have some time?

Thank you!

### CODE REVIEW

**Comment by amartinhuertas** [comment]
Hi @ericneiva ! Thanks for the PR! Do you know why it did run successfully?

**Comment by ericneiva** [comment]
Hi, @amartinhuertas, good question! I didn't look into that. I barely have experience with the transient machinery and I would need some time to figure out why the tests were passing before.

**Comment by oriolcg** [comment]
Hi @amartinhuertas @ericneiva . Thanks for spotting and fixing these typos. The definition of `ConstantMatrix` and `Constant` operators are there just to show how would it work for the respective cases. These operators are not used to get the solution and, thus, the test doesn't fail. If they would have been used, they would have failed.

**Comment by ericneiva** [comment]
Yes, exactly, @oriolcg. Thanks for clarifying this.

**Pull request merged**
