### PR TITLE
First draft/skeleton version of Poisson distributed tutorial

### PR DESCRIPTION
**Pull request by amartinhuertas**
cc @oriolcg @fverdugo @santiagobadia 

Work in progress (not ready to be merged). Pending:

1. [x] Add Example 4 code (requires a new release of `GridapGmsh`). @fverdugo
2. [x] Revise and develop further (as needed) the current structure and contents of the tutorial. @santiagobadia @fverdugo @amartinhuertas @oriolcg 
3. [x] Check that the tutorial renders ok.
4. [x] Add to tests.
5. [x] Add comments to Examples 2, 3, 4 

~We may merge even before completing the last task.~

### CODE REVIEW

**Comment by fverdugo** [comment]
BTW, with the sequential backend, one can have interactive simulations. We can take advantage of this to explain the tutorial step by step like the other ones. At the end, we can wrap the code in a function and launch it with mpi

**Comment by fverdugo** [comment]
> Ok, but this has to be in a different tutorial, right? Otherwise we cannot leverage GridapP4est.jl, GridapPETSc.jl, etc.

Except for GridapP4est.jl, the rest should work (after implementing a couple of missing methods in GridapPETSc). 

Assuming unlimited resources (which are not), it would be interesting to do a first tutorial step by step to explain the main idea behind GridapDistributed (e.g. with a Cartesian grid and a direct solver), and then have other tutorials regarding meshing  solvers etc.

**Comment by amartinhuertas** [comment]
> BTW, with the sequential backend, one can have interactive simulations.

I have mentioned this in the present tutorial (while we dont have the detailed tutorial with sequential backend)

**Comment by amartinhuertas** [comment]
> Add Example 4 code (requires a new release of GridapGmsh). @fverdugo

I am pointing in the meantime into the `gridap_distributed` branch of GridapGmsh, so that we can merge into `main` something functional (and refer to it when people ask about how to use GridapDistributed.jl)

**Comment by amartinhuertas** [comment]
> Revise and develop further (as needed) the current structure and contents of the tutorial. @santiagobadia @fverdugo @amartinhuertas @oriolcg

I have completed all the pending tasks, only a final revision is needed from your side!

**Comment by amartinhuertas** [comment]
Tests are passing now (even the MPI tutorials). It can be merged (subject to revision)

**Comment by amartinhuertas** [comment]
> GridapGmsh registered today (v0.6.0).

Ok. Thanks for letting me know.  https://github.com/gridap/Tutorials/pull/135

**Pull request merged**
