### PR TITLE
Minor fix to validation test

### PR DESCRIPTION
**Pull request by principejavier**

### CODE REVIEW

**Comment by santiagobadia** [comment]
@principejavier have you checked whether the plots are the same after this change? If not, can you update them please (and any comment abou the plots that will be out of date now)

**Comment by fverdugo** [comment]
I would change the manufactured solution for the convergence test and choose a polynomial (of one degree higher than the interpolation) instead of a trigonometric function. In that way, we can integrate exactly the manufactured solution (and the associated rhs and error norms)  with a sufficiently high degree quadrature rule and remove all the noise introduced from integration errors.

In fact, I remember that with the current manufactured solution we don't get optimal convergence for higher orders that the ones considered in the tutorial (I believe due to integration errors)

**Comment by principejavier** [comment]
> @principejavier have you checked whether the plots are the same after this change? If not, can you update them please (and any comment abou the plots that will be out of date now)

I did not, but the change I made does not change plots because in [this line]( https://github.com/gridap/Tutorials/blob/7843c80d20a586f4ad2774700352d2cb22175d33/src/validation.jl#L214) order is set to 2 and therefore degree=2*(order-1)=1. The change will only work if a higher order is used.

> In fact, I remember that with the current manufactured solution we don't get optimal convergence for higher orders that the ones considered in the tutorial (I believe due to integration errors)

Precisely, before this merge, the call 
`el2s, eh1s, hs = conv_test([8,16,32,64,128],3);`
would produce subintegration.

> I would change the manufactured solution for the convergence test and choose a polynomial (of one degree higher than the interpolation) instead of a trigonometric function. In that way, we can integrate exactly the manufactured solution (and the associated rhs and error norms) with a sufficiently high degree quadrature rule and remove all the noise introduced by integration errors.

The solution `u(x)=x[1]*(x[1]-1)*x[2]*(x[2]-1)` is an option (fourth order). It could be rised to to order÷4+1 if you want to have a general test for arbitrary order or keep it order 4 and comment in the tutorial to use order 2 or 3...it is a trade-off between generality and simplicity. What do you think? I can do it...

**Comment by santiagobadia** [comment]
A fourth order manufactured solution and a measure of the right order to integrate 8th order polynomials  (L2 norm) would be enough (I think). We can say in the tutorial that for order >=4 we get the exact solution up to rounding errors. @principejavier if you can do it, perfect. Remember to change the figures and text accordingly. Thanks!

**Review by fverdugo — CHANGES_REQUESTED** [review]
@principejavier thanks for the PR!

See the last comment by @santiagobadia above ☝️

**Comment by principejavier** [comment]
I verified that degre=2*(order-1) is not enough. The current figure (degree=2,order=2) is different from the following one (degree=4,order=2).
conv

Now the expected convegence rates of 3 and 2 for the L2 and H1 errors are obtained and degree=4 is necesary. With degree=3 (as with degree=2) the slope of the H1 error is 3. I assume that this comes from the (under)integration of the **squared** error, altough I would expected degree=3 to be enough to see a decay with slope 2 (or 3).

Am I misunderstanding the meaning of degree? Is it the degree of the polynomial you want to integrate exactly with the measure, right?

**Comment by fverdugo** [comment]
I would say that for integrating `abs2(u)`, where  `u(x)=x[1]*(x[1]-1)*x[2]*(x[2]-1)` in a Cartesian grid you need order 4 (in each spatial direction direction). So  `(degree=4,order=2)` makes sense. The formula `degre=2*(order-1)` does not work since the degree is not driven by the FE interpolation but from the exact solution (which is independent of `order` in this case).

**Comment by principejavier** [comment]
> I would say that for integrating abs2(u), where u(x)=x[1]*(x[1]-1)*x[2]*(x[2]-1) in a Cartesian grid you need order 4 (in each spatial direction). So (degree=4,order=2) makes sense. The formula degre=2*(order-1) does not work since the degree is not driven by the FE interpolation but from the exact solution (which is independent of order in this case).

I was still using the original exact solution of sin type (in the previous graph). In this case the integration error cannot be eliminated completely. But one needs at least to make it smaller than the approximation error. However, we integerate the error **squared** so using integration with degree=2*(order+1) (for any solution) would work. For the sin type solution I see that degree=2*order is enough but degree=order (as it was originally) produces the wrong slope for the H1 error.

I'm now working with `u(x)=x[1]^p+x[2]^p` and `p=4` because u(x)=x[1]*(x[1]-1)*x[2]*(x[2]-1) has a tensor product structure so you get it exactly with order=2.

In any case, the degree argument of Measure is the degree of the polynomial to be integrated exactly, righ?

**Comment by fverdugo** [comment]
> I was still using the original exact solution of sin type (in the previous graph).

OK! I was assuming that you were using the new function.

> In any case, the degree argument of Measure is the degree of the polynomial to be integrated exactly, right?

Yes! it ensures exact integration of all polynomials in Pk (simplices) or Qk (n-cubes) where k is the degree.

**Review by fverdugo — APPROVED** [review]

**Pull request merged**
