### PR TITLE
Update/structure

### PR DESCRIPTION
**Pull request by victorsndvg**
Update tutorials structure to ease contribution

### CODE REVIEW

**Comment by fverdugo** [comment]
@victorsndvg good job!

can you do these two tasks before merging?
- Rename the folders in `assets` according with the new names in `src` (essentially, remove the `t00x_` prefix)
- Could you include the header 
```md
# # TUTORIAL_TITLE
#
# BINDER_BADGE
# NBVIWER_BADGE
```
automatically in all tutorials so that we don't need to write them in all .jl files?

Thanks!

**Comment by victorsndvg** [comment]
I think your latest requests are done in commit d53474a and 7dd60ee

**Comment by fverdugo** [comment]
@victorsndvg thanks for the work!

Before merging, I need to build the documentation locally and look at it carefully.

**Comment by victorsndvg** [comment]
Perfect!

@fverdugo let me know if you find any issue

**Pull request merged**
