### PR TITLE
Adds unfitted Poisson tutorial

### PR DESCRIPTION
**Pull request by ericneiva**
Hi, I thought we could add to this repo the unfitted Poisson tutorial we have in [JourneeGridap2022](https://github.com/gridap/JourneeGridap2022). Let me know what you think of it.

### CODE REVIEW

**Comment by ericneiva** [comment]
Hello, @fverdugo, let me know what you think of this PR whenever you have some time :)

**Comment by ericneiva** [comment]
Hi, @fverdugo,

This PR is now ready for merge.

However, MPI tests fail. I think it's related to PartitionedArrays. If I downgrade to 0.2.11 tests pass.

Do you or @amartinhuertas have any idea how to fix this?

**Comment by amartinhuertas** [comment]
> Do you or @amartinhuertas have any idea how to fix this?

Hi @ericneiva ... can you please remove the deprecated warnings as @JordiManyer did here in this PR with `GridapDistributed.jl`: 

https://github.com/gridap/GridapDistributed.jl/pull/104/files ? 

If am not wrong, after doing this, the error should disappear.

**Comment by ericneiva** [comment]
> If am not wrong, after doing this, the error should disappear.

Indeed. Thanks, @amartinhuertas.

If there are no other comments, this PR is ready for merge.

**Pull request merged**
